# Generated by Django 4.2.29 on 2026-04-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rtl', models.BooleanField(default=False)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('auto_translated', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='i18n_app.language')),
            ],
            options={
                'unique_together': {('language', 'key')},
            },
        ),
    ]
