# Generated by Django 4.2.29 on 2026-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TEKNOFEST Ulaşım Sistemi', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#7C3AED', max_length=7)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('email_from_name', models.CharField(default='TEKNOFEST', max_length=100)),
                ('magic_link_subject', models.CharField(default='TEKNOFEST - Giriş Linki', max_length=200)),
                ('magic_link_body', models.TextField(default='Merhaba {name},\n\nGiriş: {link}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
