# Generated by Django 4.2.29 on 2026-04-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_supported_members', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_code', models.CharField(max_length=50, unique=True)),
                ('supported_member_count', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tc_id', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('transport_type', models.CharField(choices=[('plane', 'Uçak'), ('bus', 'Otobüs'), ('train', 'Tren'), ('other', 'Diğer'), ('none', 'Talep Yok')], max_length=20)),
                ('is_supported', models.BooleanField(default=False)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('kys_id', models.CharField(blank=True, max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
