# Generated by Django 4.2.29 on 2026-04-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0002_participant_city_from_participant_city_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='arrival_earliest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='arrival_latest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='departure_earliest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='departure_latest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_supported',
            field=models.BooleanField(default=True),
        ),
    ]
