# Generated by Django 4.2.29 on 2026-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/')),
                ('ai_extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_extracted_date', models.DateField(blank=True, null=True)),
                ('ai_extracted_owner', models.CharField(blank=True, max_length=255)),
                ('ai_extracted_transport_type', models.CharField(blank=True, max_length=50)),
                ('ai_extracted_origin', models.CharField(blank=True, max_length=100)),
                ('ai_extracted_destination', models.CharField(blank=True, max_length=100)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_raw_response', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('manual_review', 'Manuel inceleme'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('rejection_reasons', models.JSONField(default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
