# Generated by Django 4.2.29 on 2026-04-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0003_competition_arrival_earliest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('plane', 'Uçak'), ('bus', 'Otobüs'), ('train', 'Tren'), ('self', 'Kendi İmkanımla')], default='bus', max_length=20)),
                ('preferred_arrival_date', models.DateField(blank=True, null=True)),
                ('preferred_departure_date', models.DateField(blank=True, null=True)),
                ('flight_notes', models.TextField(blank=True)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('info_collected', 'Bilgiler alındı'), ('invoice_uploaded', 'Fatura yüklendi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('plane_confirmed', 'Uçak bileti alındı'), ('self_noted', 'Kendi imkanı')], default='pending', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_request', to='competitions.participant')),
            ],
        ),
    ]
