# Generated by Django 4.2.29 on 2026-04-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_participant_city_from_participant_city_to_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='supported_quota_override',
            field=models.PositiveIntegerField(blank=True, help_text='Formdan gelen desteklenecek kişi üst sınırı (boşsa yarışma değeri)', null=True),
        ),
        migrations.AddField(
            model_name='ticketsubmission',
            name='account_holder_tc',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='ticketsubmission',
            name='basvuru_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketsubmission',
            name='invoice_drive_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ticketsubmission',
            name='payment_form_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Google Form satırından gelen özet (rapor için)'),
        ),
        migrations.AlterField(
            model_name='ticketsubmission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_submissions', to='competitions.participant'),
        ),
    ]
